const invitees = [
  { id: 1, name: 'Danci Crina', fromWho: 'groom', numberOfNights: 2 },
  { id: 2, name: 'Danci Andrei', fromWho: 'groom', numberOfNights: 2 },
  { id: 3, name: 'Paul Ananie', fromWho: 'groom', numberOfNights: 2 },
  { id: 5, name: 'Vișovan Aurelia', fromWho: 'groom', numberOfNights: 2 },
  { id: 6, name: 'Çakmur Can', fromWho: 'groom', notes: 'prietenul Aureliei Vișovan', numberOfNights: 2 },
  { id: 7, name: 'Mîcnea Iulian', fromWho: 'groom', numberOfNights: 2 },
  { id: 8, name: 'Elena Geartu', fromWho: 'groom', notes: 'prietena lui Iulian Mîcnea', numberOfNights: 2 },
  { id: 11, name: 'Balasz Doina', fromWho: 'groom', numberOfNights: 1 },
  { id: 12, name: 'Ilnițchi Radu', fromWho: 'groom', notes: 'soțul Doinei Balasz', numberOfNights: 1 },
  { id: 17, name: 'Hajdu Romina', fromWho: 'groom', notes: '"Romina Carpiuc"', numberOfNights: 1 },
  { id: 18, name: 'Hajdu Istvan', fromWho: 'groom', numberOfNights: 1 },
  { id: 21, name: 'Haidu Romulus (Romi)', fromWho: 'groom', numberOfNights: 1 },
  { id: 22, name: 'Haidu Diana', fromWho: 'groom', numberOfNights: 1 },
  { id: 23, name: 'Haidu Luca', fromWho: 'groom', notes: 'copil cls 5-a', numberOfNights: 1 },
  { id: 26, name: 'Mursa Cătălin', fromWho: 'groom', numberOfNights: 1 },
  { id: 28, name: 'Spiridon Iulian Marian', fromWho: 'groom', numberOfNights: 1 },
  { id: 100, name: 'Gherasim Mirabela', notes: '', numberOfNights: 2 },
  { id: 101, name: 'Carcea Ionuț', notes: 'prietenul Mirabelei Gherasim', numberOfNights: 2 },
  { id: 102, name: 'Țăruș Andreea', notes: '', numberOfNights: 2 },
  { id: 103, name: 'Vieru Ilie', notes: 'prietenul Andreei Țăruș', numberOfNights: 2 },
  { id: 104, name: 'Ciobanu Alexandra', notes: '"Alexandra Manolache" + bebe 4 luni', numberOfNights: 2 },
  { id: 105, name: 'Ciobanu Gheorghiță', notes: 'Sâmbătă + Duminică!', numberOfNights: 2 },
  { id: 106, name: 'Roșca Daniel', notes: '', numberOfNights: 1 },
  { id: 107, name: 'Angheluță Teodora', notes: 'iubita lui Daniel Roșca', numberOfNights: 1 },
  { id: 108, name: 'Vrînceanu George', notes: '', numberOfNights: 1 },
  { id: 109, name: 'Baroi Arianna', notes: 'iubita lui Vrînceanu George', numberOfNights: 1 },
  { id: 110, name: 'Iacob Bogdan', notes: '', numberOfNights: 1 },
  { id: 111, name: 'Lupu Maria', notes: 'iubita lui Bogdan Iacob', numberOfNights: 1 },
  { id: 114, name: 'Lipovanu Dorin', notes: 'fratele mamei miresei', numberOfNights: 1 },
  { id: 115, name: 'Lipovanu Darius', notes: 'clasa a 10-a', numberOfNights: 1 },
  { id: 116, name: 'Lipovanu Cristina', notes: '+ copil Iustin 4 ani', numberOfNights: 1 },
  { id: 117, name: 'Constantiniu Iuliana', notes: '"Coca Marțin"', numberOfNights: 2 },
  { id: 118, name: 'Constantiniu Tudor', notes: '', numberOfNights: 2 },
  { id: 119, name: 'Constantiniu Matei', notes: 'cls 10-a', numberOfNights: 2 },
  { id: 121, name: 'Lucan Valerica', notes: '', numberOfNights: 2 },
  { id: 122, name: 'Cilof Costel', notes: 'iubitul Valericăi Lucan', numberOfNights: 2 },
  { id: 125, name: 'Marțin Elena', notes: '', numberOfNights: 2 },
  { id: 126, name: 'Lucan Alexandra', notes: '', numberOfNights: 2 },
  { id: 127, name: 'Bodea Andrei Ionuț', notes: 'iubitul Alexandrei Lucan', numberOfNights: 2 },
  { id: 128, name: 'Lucan Daniel', notes: '', numberOfNights: 2 },
  { id: 129, name: 'Bazga Elena-Petronela', notes: 'iubita lu Daniel Lucan', numberOfNights: 2 },
  { id: 130, name: 'Lucan Lenuța', notes: '', numberOfNights: 2 },
  { id: 131, name: 'Lucan Petrișor', numberOfNights: 2, notes: 'verișor' },
  { id: 132, name: 'Marțin Gabi', notes: '', numberOfNights: 2 },
  { id: 133, name: 'Marțin Călina', notes: '', numberOfNights: 2 },
  { id: 136, name: 'Țuțuianu Iuliana', notes: '"Iuliana Axinte"', numberOfNights: 2 },
  { id: 137, name: 'Țuțuianu Ovidiu', notes: '', numberOfNights: 2 },
  { id: 142, name: 'Mandric Gabriela', notes: '"Gabi Andrioaie" + copil 3 luni', numberOfNights: 2 },
  { id: 143, name: 'Mandric Cătălin', notes: '', numberOfNights: 2 },
  { id: 152, name: 'Mătase Mihaela', notes: '', numberOfNights: 2 },
  { id: 153, name: 'Mătase Puiu', notes: '', numberOfNights: 2 },
  { id: 158, name: 'Chelciuc Mihaela', notes: '', numberOfNights: 1 },
  { id: 159, name: 'Agache Bogdan', notes: 'iubitul Mihaelei Chelciuc', numberOfNights: 1 },
  { id: 160, name: 'Taraf 1',   numberOfNights: 1 },
  { id: 161, name: 'Taraf 2',   numberOfNights: 1 },
  { id: 162, name: 'Taraf 3',   numberOfNights: 1 },
  { id: 163, name: 'Taraf 4',   numberOfNights: 1 },
];

export default invitees;
